"""initial analytics schema

Revision ID: 766d4d39b615
Revises: 
Create Date: 2026-05-19 19:24:08.339533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '766d4d39b615'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grid_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reading_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('as_at_time', sa.String(length=16), nullable=True),
    sa.Column('total_generation_mw', sa.Float(), nullable=False),
    sa.Column('reporting_gencos', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('daily_json', sa.JSON(), nullable=False),
    sa.Column('disco_as_at', sa.String(length=255), nullable=True),
    sa.Column('total_load_allocation_mw', sa.Float(), nullable=True),
    sa.Column('raw_payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grid_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grid_snapshots_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_grid_snapshots_reading_timestamp'), ['reading_timestamp'], unique=True)
        batch_op.create_index(batch_op.f('ix_grid_snapshots_total_generation_mw'), ['total_generation_mw'], unique=False)

    op.create_table('analytics_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_hours', sa.Integer(), nullable=False),
    sa.Column('trend_json', sa.JSON(), nullable=False),
    sa.Column('volatility_json', sa.JSON(), nullable=False),
    sa.Column('health_json', sa.JSON(), nullable=False),
    sa.Column('stability_json', sa.JSON(), nullable=False),
    sa.Column('outage_json', sa.JSON(), nullable=False),
    sa.Column('concentration_json', sa.JSON(), nullable=False),
    sa.Column('top_gencos_json', sa.JSON(), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['grid_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'window_hours', name='uq_analytics_snapshot_window')
    )
    with op.batch_alter_table('analytics_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_snapshots_calculated_at'), ['calculated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_snapshots_snapshot_id'), ['snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_snapshots_window_hours'), ['window_hours'], unique=False)

    op.create_table('disco_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('load_allocation_mw', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['grid_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'company', name='uq_disco_snapshot_company')
    )
    with op.batch_alter_table('disco_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disco_data_company'), ['company'], unique=False)
        batch_op.create_index(batch_op.f('ix_disco_data_snapshot_id'), ['snapshot_id'], unique=False)

    op.create_table('genco_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('plant', sa.String(length=255), nullable=False),
    sa.Column('generation_mw', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['grid_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'plant', name='uq_genco_snapshot_plant')
    )
    with op.batch_alter_table('genco_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_genco_data_plant'), ['plant'], unique=False)
        batch_op.create_index(batch_op.f('ix_genco_data_snapshot_id'), ['snapshot_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genco_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_genco_data_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_genco_data_plant'))

    op.drop_table('genco_data')
    with op.batch_alter_table('disco_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disco_data_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_disco_data_company'))

    op.drop_table('disco_data')
    with op.batch_alter_table('analytics_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_snapshots_window_hours'))
        batch_op.drop_index(batch_op.f('ix_analytics_snapshots_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_analytics_snapshots_calculated_at'))

    op.drop_table('analytics_snapshots')
    with op.batch_alter_table('grid_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grid_snapshots_total_generation_mw'))
        batch_op.drop_index(batch_op.f('ix_grid_snapshots_reading_timestamp'))
        batch_op.drop_index(batch_op.f('ix_grid_snapshots_captured_at'))

    op.drop_table('grid_snapshots')
    # ### end Alembic commands ###
